// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

import (
	"time"
)

const TableNameAlphaAmmPool = "alpha_amm_pool"

// AlphaAmmPool LP流动性池
type AlphaAmmPool struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ChainID         int32     `gorm:"column:chain_id;not null;comment:链ID (如 1: Ethereum, 56: BSC)" json:"chain_id"` // 链ID (如 1: Ethereum, 56: BSC)
	PoolAddress     string    `gorm:"column:pool_address;not null" json:"pool_address"`
	Token0Address   string    `gorm:"column:token0_address;not null" json:"token0_address"`
	Token1Address   string    `gorm:"column:token1_address;not null" json:"token1_address"`
	PoolType        string    `gorm:"column:pool_type;not null" json:"pool_type"`
	FeeTier         int32     `gorm:"column:fee_tier" json:"fee_tier"`
	TickSpace       int32     `gorm:"column:tick_space" json:"tick_space"`
	Reserve0        string    `gorm:"column:reserve0;comment:V2: Token0 余额" json:"reserve0"`                  // V2: Token0 余额
	Reserve1        string    `gorm:"column:reserve1;comment:V2: Token1 余额" json:"reserve1"`                  // V2: Token1 余额
	Price0          string    `gorm:"column:price0;comment:Token0 价格" json:"price0"`                          // Token0 价格
	Price1          string    `gorm:"column:price1;comment:Token1 价格" json:"price1"`                          // Token1 价格
	Liquidity       string    `gorm:"column:liquidity;comment:V3: 活跃流动性 (uint128/256)" json:"liquidity"`      // V3: 活跃流动性 (uint128/256)
	SqrtPriceX96    string    `gorm:"column:sqrt_price_x96;comment:V3: 价格标识 (uint256)" json:"sqrt_price_x96"` // V3: 价格标识 (uint256)
	CurrentTick     int32     `gorm:"column:current_tick;comment:V3: 当前Tick" json:"current_tick"`             // V3: 当前Tick
	LastBlockNumber int64     `gorm:"column:last_block_number;comment:最后一次更新的区块高度" json:"last_block_number"`  // 最后一次更新的区块高度
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	LastUpdatedAt   time.Time `gorm:"column:last_updated_at;default:CURRENT_TIMESTAMP" json:"last_updated_at"`
}

// TableName AlphaAmmPool's table name
func (*AlphaAmmPool) TableName() string {
	return TableNameAlphaAmmPool
}
