// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

import (
	"time"
)

const TableNameAlphaToken = "alpha_token"

// AlphaToken token信息表
type AlphaToken struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Symbol    string    `gorm:"column:symbol;not null" json:"symbol"`
	Name      string    `gorm:"column:name" json:"name"`
	Address   string    `gorm:"column:address" json:"address"`
	IsNative  bool      `gorm:"column:is_native;comment:是否是原生代币" json:"is_native"` // 是否是原生代币
	Decimals  int32     `gorm:"column:decimals;not null" json:"decimals"`
	ChainID   string    `gorm:"column:chain_id;not null" json:"chain_id"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName AlphaToken's table name
func (*AlphaToken) TableName() string {
	return TableNameAlphaToken
}
