// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

import (
	"time"
)

const TableNameAlphaPoolLiquidityEvent = "alpha_pool_liquidity_event"

// AlphaPoolLiquidityEvent LP流动性增减事件记录表
type AlphaPoolLiquidityEvent struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ChainID        int32     `gorm:"column:chain_id;not null;comment:链ID" json:"chain_id"`                                    // 链ID
	PoolAddress    string    `gorm:"column:pool_address;not null;comment:池子地址" json:"pool_address"`                           // 池子地址
	TxHash         string    `gorm:"column:tx_hash;not null;comment:交易哈希" json:"tx_hash"`                                     // 交易哈希
	LogIndex       int32     `gorm:"column:log_index;not null;comment:日志索引(防单笔交易多事件)" json:"log_index"`                       // 日志索引(防单笔交易多事件)
	EventName      string    `gorm:"column:event_name;not null;comment:MINT:添加, BURN:移除, COLLECT:提取收益(V3)" json:"event_name"` // MINT:添加, BURN:移除, COLLECT:提取收益(V3)
	Provider       string    `gorm:"column:provider;not null;comment:流动性提供者地址" json:"provider"`                               // 流动性提供者地址
	Amount0        string    `gorm:"column:amount0;comment:Token0 变动数量" json:"amount0"`                                       // Token0 变动数量
	Amount1        string    `gorm:"column:amount1;comment:Token1 变动数量" json:"amount1"`                                       // Token1 变动数量
	TickLower      int32     `gorm:"column:tick_lower;comment:V3: 价格区间下限" json:"tick_lower"`                                  // V3: 价格区间下限
	TickUpper      int32     `gorm:"column:tick_upper;comment:V3: 价格区间上限" json:"tick_upper"`                                  // V3: 价格区间上限
	LiquidityDelta string    `gorm:"column:liquidity_delta;comment:V3: 流动性数量变化(sqrt)" json:"liquidity_delta"`                 // V3: 流动性数量变化(sqrt)
	BlockNumber    int64     `gorm:"column:block_number;not null;comment:区块高度" json:"block_number"`                           // 区块高度
	BlockTimestamp time.Time `gorm:"column:block_timestamp;not null;comment:区块时间(由链上提供)" json:"block_timestamp"`              // 区块时间(由链上提供)
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName AlphaPoolLiquidityEvent's table name
func (*AlphaPoolLiquidityEvent) TableName() string {
	return TableNameAlphaPoolLiquidityEvent
}
