// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

import (
	"time"
)

const TableNameAlphaAmmV3PoolTick = "alpha_amm_v3_pool_tick"

// AlphaAmmV3PoolTick mapped from table <alpha_amm_v3_pool_tick>
type AlphaAmmV3PoolTick struct {
	ID                    int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ChainID               int32     `gorm:"column:chain_id;not null" json:"chain_id"`
	PoolAddress           string    `gorm:"column:pool_address;not null" json:"pool_address"`
	TickIndex             int32     `gorm:"column:tick_index;not null" json:"tick_index"`
	LiquidityGross        string    `gorm:"column:liquidity_gross;not null" json:"liquidity_gross"`
	LiquidityNet          string    `gorm:"column:liquidity_net;not null" json:"liquidity_net"`
	FeeGrowthOutside0X128 string    `gorm:"column:fee_growth_outside0_x128;not null" json:"fee_growth_outside0_x128"`
	FeeGrowthOutside1X128 string    `gorm:"column:fee_growth_outside1_x128;not null" json:"fee_growth_outside1_x128"`
	CreatedAt             time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	LastUpdatedAt         time.Time `gorm:"column:last_updated_at;default:CURRENT_TIMESTAMP" json:"last_updated_at"`
}

// TableName AlphaAmmV3PoolTick's table name
func (*AlphaAmmV3PoolTick) TableName() string {
	return TableNameAlphaAmmV3PoolTick
}
