// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

import (
	"time"
)

const TableNameConfigPair = "config_pair"

// ConfigPair mapped from table <config_pair>
type ConfigPair struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Token0Address string    `gorm:"column:token0_address;not null" json:"token0_address"`
	Token1Address string    `gorm:"column:token1_address;not null" json:"token1_address"`
	FeeTier       int32     `gorm:"column:fee_tier" json:"fee_tier"`
	TickSpace     int32     `gorm:"column:tick_space" json:"tick_space"`
	PoolType      string    `gorm:"column:pool_type;not null" json:"pool_type"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName ConfigPair's table name
func (*ConfigPair) TableName() string {
	return TableNameConfigPair
}
