// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"alpha-amm-engine/internal/dao/sqlmodel"
)

func newAlphaAmmPool(db *gorm.DB, opts ...gen.DOOption) alphaAmmPool {
	_alphaAmmPool := alphaAmmPool{}

	_alphaAmmPool.alphaAmmPoolDo.UseDB(db, opts...)
	_alphaAmmPool.alphaAmmPoolDo.UseModel(&sqlmodel.AlphaAmmPool{})

	tableName := _alphaAmmPool.alphaAmmPoolDo.TableName()
	_alphaAmmPool.ALL = field.NewAsterisk(tableName)
	_alphaAmmPool.ID = field.NewInt64(tableName, "id")
	_alphaAmmPool.ChainID = field.NewInt32(tableName, "chain_id")
	_alphaAmmPool.PoolAddress = field.NewString(tableName, "pool_address")
	_alphaAmmPool.Token0Address = field.NewString(tableName, "token0_address")
	_alphaAmmPool.Token1Address = field.NewString(tableName, "token1_address")
	_alphaAmmPool.PoolType = field.NewString(tableName, "pool_type")
	_alphaAmmPool.FeeTier = field.NewInt32(tableName, "fee_tier")
	_alphaAmmPool.TickSpace = field.NewInt32(tableName, "tick_space")
	_alphaAmmPool.Reserve0 = field.NewString(tableName, "reserve0")
	_alphaAmmPool.Reserve1 = field.NewString(tableName, "reserve1")
	_alphaAmmPool.Price0 = field.NewString(tableName, "price0")
	_alphaAmmPool.Price1 = field.NewString(tableName, "price1")
	_alphaAmmPool.Liquidity = field.NewString(tableName, "liquidity")
	_alphaAmmPool.SqrtPriceX96 = field.NewString(tableName, "sqrt_price_x96")
	_alphaAmmPool.CurrentTick = field.NewInt32(tableName, "current_tick")
	_alphaAmmPool.LastBlockNumber = field.NewInt64(tableName, "last_block_number")
	_alphaAmmPool.CreatedAt = field.NewTime(tableName, "created_at")
	_alphaAmmPool.LastUpdatedAt = field.NewTime(tableName, "last_updated_at")

	_alphaAmmPool.fillFieldMap()

	return _alphaAmmPool
}

// alphaAmmPool LP流动性池
type alphaAmmPool struct {
	alphaAmmPoolDo alphaAmmPoolDo

	ALL             field.Asterisk
	ID              field.Int64
	ChainID         field.Int32 // 链ID (如 1: Ethereum, 56: BSC)
	PoolAddress     field.String
	Token0Address   field.String
	Token1Address   field.String
	PoolType        field.String
	FeeTier         field.Int32
	TickSpace       field.Int32
	Reserve0        field.String // V2: Token0 余额
	Reserve1        field.String // V2: Token1 余额
	Price0          field.String // Token0 价格
	Price1          field.String // Token1 价格
	Liquidity       field.String // V3: 活跃流动性 (uint128/256)
	SqrtPriceX96    field.String // V3: 价格标识 (uint256)
	CurrentTick     field.Int32  // V3: 当前Tick
	LastBlockNumber field.Int64  // 最后一次更新的区块高度
	CreatedAt       field.Time
	LastUpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (a alphaAmmPool) Table(newTableName string) *alphaAmmPool {
	a.alphaAmmPoolDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alphaAmmPool) As(alias string) *alphaAmmPool {
	a.alphaAmmPoolDo.DO = *(a.alphaAmmPoolDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alphaAmmPool) updateTableName(table string) *alphaAmmPool {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.ChainID = field.NewInt32(table, "chain_id")
	a.PoolAddress = field.NewString(table, "pool_address")
	a.Token0Address = field.NewString(table, "token0_address")
	a.Token1Address = field.NewString(table, "token1_address")
	a.PoolType = field.NewString(table, "pool_type")
	a.FeeTier = field.NewInt32(table, "fee_tier")
	a.TickSpace = field.NewInt32(table, "tick_space")
	a.Reserve0 = field.NewString(table, "reserve0")
	a.Reserve1 = field.NewString(table, "reserve1")
	a.Price0 = field.NewString(table, "price0")
	a.Price1 = field.NewString(table, "price1")
	a.Liquidity = field.NewString(table, "liquidity")
	a.SqrtPriceX96 = field.NewString(table, "sqrt_price_x96")
	a.CurrentTick = field.NewInt32(table, "current_tick")
	a.LastBlockNumber = field.NewInt64(table, "last_block_number")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.LastUpdatedAt = field.NewTime(table, "last_updated_at")

	a.fillFieldMap()

	return a
}

func (a *alphaAmmPool) WithContext(ctx context.Context) IAlphaAmmPoolDo {
	return a.alphaAmmPoolDo.WithContext(ctx)
}

func (a alphaAmmPool) TableName() string { return a.alphaAmmPoolDo.TableName() }

func (a alphaAmmPool) Alias() string { return a.alphaAmmPoolDo.Alias() }

func (a alphaAmmPool) Columns(cols ...field.Expr) gen.Columns {
	return a.alphaAmmPoolDo.Columns(cols...)
}

func (a *alphaAmmPool) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alphaAmmPool) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 18)
	a.fieldMap["id"] = a.ID
	a.fieldMap["chain_id"] = a.ChainID
	a.fieldMap["pool_address"] = a.PoolAddress
	a.fieldMap["token0_address"] = a.Token0Address
	a.fieldMap["token1_address"] = a.Token1Address
	a.fieldMap["pool_type"] = a.PoolType
	a.fieldMap["fee_tier"] = a.FeeTier
	a.fieldMap["tick_space"] = a.TickSpace
	a.fieldMap["reserve0"] = a.Reserve0
	a.fieldMap["reserve1"] = a.Reserve1
	a.fieldMap["price0"] = a.Price0
	a.fieldMap["price1"] = a.Price1
	a.fieldMap["liquidity"] = a.Liquidity
	a.fieldMap["sqrt_price_x96"] = a.SqrtPriceX96
	a.fieldMap["current_tick"] = a.CurrentTick
	a.fieldMap["last_block_number"] = a.LastBlockNumber
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["last_updated_at"] = a.LastUpdatedAt
}

func (a alphaAmmPool) clone(db *gorm.DB) alphaAmmPool {
	a.alphaAmmPoolDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alphaAmmPool) replaceDB(db *gorm.DB) alphaAmmPool {
	a.alphaAmmPoolDo.ReplaceDB(db)
	return a
}

type alphaAmmPoolDo struct{ gen.DO }

type IAlphaAmmPoolDo interface {
	gen.SubQuery
	Debug() IAlphaAmmPoolDo
	WithContext(ctx context.Context) IAlphaAmmPoolDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlphaAmmPoolDo
	WriteDB() IAlphaAmmPoolDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlphaAmmPoolDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlphaAmmPoolDo
	Not(conds ...gen.Condition) IAlphaAmmPoolDo
	Or(conds ...gen.Condition) IAlphaAmmPoolDo
	Select(conds ...field.Expr) IAlphaAmmPoolDo
	Where(conds ...gen.Condition) IAlphaAmmPoolDo
	Order(conds ...field.Expr) IAlphaAmmPoolDo
	Distinct(cols ...field.Expr) IAlphaAmmPoolDo
	Omit(cols ...field.Expr) IAlphaAmmPoolDo
	Join(table schema.Tabler, on ...field.Expr) IAlphaAmmPoolDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlphaAmmPoolDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlphaAmmPoolDo
	Group(cols ...field.Expr) IAlphaAmmPoolDo
	Having(conds ...gen.Condition) IAlphaAmmPoolDo
	Limit(limit int) IAlphaAmmPoolDo
	Offset(offset int) IAlphaAmmPoolDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlphaAmmPoolDo
	Unscoped() IAlphaAmmPoolDo
	Create(values ...*sqlmodel.AlphaAmmPool) error
	CreateInBatches(values []*sqlmodel.AlphaAmmPool, batchSize int) error
	Save(values ...*sqlmodel.AlphaAmmPool) error
	First() (*sqlmodel.AlphaAmmPool, error)
	Take() (*sqlmodel.AlphaAmmPool, error)
	Last() (*sqlmodel.AlphaAmmPool, error)
	Find() ([]*sqlmodel.AlphaAmmPool, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlmodel.AlphaAmmPool, err error)
	FindInBatches(result *[]*sqlmodel.AlphaAmmPool, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*sqlmodel.AlphaAmmPool) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlphaAmmPoolDo
	Assign(attrs ...field.AssignExpr) IAlphaAmmPoolDo
	Joins(fields ...field.RelationField) IAlphaAmmPoolDo
	Preload(fields ...field.RelationField) IAlphaAmmPoolDo
	FirstOrInit() (*sqlmodel.AlphaAmmPool, error)
	FirstOrCreate() (*sqlmodel.AlphaAmmPool, error)
	FindByPage(offset int, limit int) (result []*sqlmodel.AlphaAmmPool, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlphaAmmPoolDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alphaAmmPoolDo) Debug() IAlphaAmmPoolDo {
	return a.withDO(a.DO.Debug())
}

func (a alphaAmmPoolDo) WithContext(ctx context.Context) IAlphaAmmPoolDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alphaAmmPoolDo) ReadDB() IAlphaAmmPoolDo {
	return a.Clauses(dbresolver.Read)
}

func (a alphaAmmPoolDo) WriteDB() IAlphaAmmPoolDo {
	return a.Clauses(dbresolver.Write)
}

func (a alphaAmmPoolDo) Session(config *gorm.Session) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Session(config))
}

func (a alphaAmmPoolDo) Clauses(conds ...clause.Expression) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alphaAmmPoolDo) Returning(value interface{}, columns ...string) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alphaAmmPoolDo) Not(conds ...gen.Condition) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alphaAmmPoolDo) Or(conds ...gen.Condition) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alphaAmmPoolDo) Select(conds ...field.Expr) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alphaAmmPoolDo) Where(conds ...gen.Condition) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alphaAmmPoolDo) Order(conds ...field.Expr) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alphaAmmPoolDo) Distinct(cols ...field.Expr) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alphaAmmPoolDo) Omit(cols ...field.Expr) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alphaAmmPoolDo) Join(table schema.Tabler, on ...field.Expr) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alphaAmmPoolDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlphaAmmPoolDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alphaAmmPoolDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlphaAmmPoolDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alphaAmmPoolDo) Group(cols ...field.Expr) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alphaAmmPoolDo) Having(conds ...gen.Condition) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alphaAmmPoolDo) Limit(limit int) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alphaAmmPoolDo) Offset(offset int) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alphaAmmPoolDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alphaAmmPoolDo) Unscoped() IAlphaAmmPoolDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alphaAmmPoolDo) Create(values ...*sqlmodel.AlphaAmmPool) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alphaAmmPoolDo) CreateInBatches(values []*sqlmodel.AlphaAmmPool, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alphaAmmPoolDo) Save(values ...*sqlmodel.AlphaAmmPool) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alphaAmmPoolDo) First() (*sqlmodel.AlphaAmmPool, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaAmmPool), nil
	}
}

func (a alphaAmmPoolDo) Take() (*sqlmodel.AlphaAmmPool, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaAmmPool), nil
	}
}

func (a alphaAmmPoolDo) Last() (*sqlmodel.AlphaAmmPool, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaAmmPool), nil
	}
}

func (a alphaAmmPoolDo) Find() ([]*sqlmodel.AlphaAmmPool, error) {
	result, err := a.DO.Find()
	return result.([]*sqlmodel.AlphaAmmPool), err
}

func (a alphaAmmPoolDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlmodel.AlphaAmmPool, err error) {
	buf := make([]*sqlmodel.AlphaAmmPool, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alphaAmmPoolDo) FindInBatches(result *[]*sqlmodel.AlphaAmmPool, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alphaAmmPoolDo) Attrs(attrs ...field.AssignExpr) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alphaAmmPoolDo) Assign(attrs ...field.AssignExpr) IAlphaAmmPoolDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alphaAmmPoolDo) Joins(fields ...field.RelationField) IAlphaAmmPoolDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alphaAmmPoolDo) Preload(fields ...field.RelationField) IAlphaAmmPoolDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alphaAmmPoolDo) FirstOrInit() (*sqlmodel.AlphaAmmPool, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaAmmPool), nil
	}
}

func (a alphaAmmPoolDo) FirstOrCreate() (*sqlmodel.AlphaAmmPool, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaAmmPool), nil
	}
}

func (a alphaAmmPoolDo) FindByPage(offset int, limit int) (result []*sqlmodel.AlphaAmmPool, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alphaAmmPoolDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alphaAmmPoolDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alphaAmmPoolDo) Delete(models ...*sqlmodel.AlphaAmmPool) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alphaAmmPoolDo) withDO(do gen.Dao) *alphaAmmPoolDo {
	a.DO = *do.(*gen.DO)
	return a
}
