// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"alpha-amm-engine/internal/dao/sqlmodel"
)

func newAlphaAmmV3PoolTick(db *gorm.DB, opts ...gen.DOOption) alphaAmmV3PoolTick {
	_alphaAmmV3PoolTick := alphaAmmV3PoolTick{}

	_alphaAmmV3PoolTick.alphaAmmV3PoolTickDo.UseDB(db, opts...)
	_alphaAmmV3PoolTick.alphaAmmV3PoolTickDo.UseModel(&sqlmodel.AlphaAmmV3PoolTick{})

	tableName := _alphaAmmV3PoolTick.alphaAmmV3PoolTickDo.TableName()
	_alphaAmmV3PoolTick.ALL = field.NewAsterisk(tableName)
	_alphaAmmV3PoolTick.ID = field.NewInt64(tableName, "id")
	_alphaAmmV3PoolTick.ChainID = field.NewInt32(tableName, "chain_id")
	_alphaAmmV3PoolTick.PoolAddress = field.NewString(tableName, "pool_address")
	_alphaAmmV3PoolTick.TickIndex = field.NewInt32(tableName, "tick_index")
	_alphaAmmV3PoolTick.LiquidityGross = field.NewString(tableName, "liquidity_gross")
	_alphaAmmV3PoolTick.LiquidityNet = field.NewString(tableName, "liquidity_net")
	_alphaAmmV3PoolTick.FeeGrowthOutside0X128 = field.NewString(tableName, "fee_growth_outside0_x128")
	_alphaAmmV3PoolTick.FeeGrowthOutside1X128 = field.NewString(tableName, "fee_growth_outside1_x128")
	_alphaAmmV3PoolTick.CreatedAt = field.NewTime(tableName, "created_at")
	_alphaAmmV3PoolTick.LastUpdatedAt = field.NewTime(tableName, "last_updated_at")

	_alphaAmmV3PoolTick.fillFieldMap()

	return _alphaAmmV3PoolTick
}

type alphaAmmV3PoolTick struct {
	alphaAmmV3PoolTickDo alphaAmmV3PoolTickDo

	ALL                   field.Asterisk
	ID                    field.Int64
	ChainID               field.Int32
	PoolAddress           field.String
	TickIndex             field.Int32
	LiquidityGross        field.String
	LiquidityNet          field.String
	FeeGrowthOutside0X128 field.String
	FeeGrowthOutside1X128 field.String
	CreatedAt             field.Time
	LastUpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (a alphaAmmV3PoolTick) Table(newTableName string) *alphaAmmV3PoolTick {
	a.alphaAmmV3PoolTickDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alphaAmmV3PoolTick) As(alias string) *alphaAmmV3PoolTick {
	a.alphaAmmV3PoolTickDo.DO = *(a.alphaAmmV3PoolTickDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alphaAmmV3PoolTick) updateTableName(table string) *alphaAmmV3PoolTick {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.ChainID = field.NewInt32(table, "chain_id")
	a.PoolAddress = field.NewString(table, "pool_address")
	a.TickIndex = field.NewInt32(table, "tick_index")
	a.LiquidityGross = field.NewString(table, "liquidity_gross")
	a.LiquidityNet = field.NewString(table, "liquidity_net")
	a.FeeGrowthOutside0X128 = field.NewString(table, "fee_growth_outside0_x128")
	a.FeeGrowthOutside1X128 = field.NewString(table, "fee_growth_outside1_x128")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.LastUpdatedAt = field.NewTime(table, "last_updated_at")

	a.fillFieldMap()

	return a
}

func (a *alphaAmmV3PoolTick) WithContext(ctx context.Context) IAlphaAmmV3PoolTickDo {
	return a.alphaAmmV3PoolTickDo.WithContext(ctx)
}

func (a alphaAmmV3PoolTick) TableName() string { return a.alphaAmmV3PoolTickDo.TableName() }

func (a alphaAmmV3PoolTick) Alias() string { return a.alphaAmmV3PoolTickDo.Alias() }

func (a alphaAmmV3PoolTick) Columns(cols ...field.Expr) gen.Columns {
	return a.alphaAmmV3PoolTickDo.Columns(cols...)
}

func (a *alphaAmmV3PoolTick) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alphaAmmV3PoolTick) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["chain_id"] = a.ChainID
	a.fieldMap["pool_address"] = a.PoolAddress
	a.fieldMap["tick_index"] = a.TickIndex
	a.fieldMap["liquidity_gross"] = a.LiquidityGross
	a.fieldMap["liquidity_net"] = a.LiquidityNet
	a.fieldMap["fee_growth_outside0_x128"] = a.FeeGrowthOutside0X128
	a.fieldMap["fee_growth_outside1_x128"] = a.FeeGrowthOutside1X128
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["last_updated_at"] = a.LastUpdatedAt
}

func (a alphaAmmV3PoolTick) clone(db *gorm.DB) alphaAmmV3PoolTick {
	a.alphaAmmV3PoolTickDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alphaAmmV3PoolTick) replaceDB(db *gorm.DB) alphaAmmV3PoolTick {
	a.alphaAmmV3PoolTickDo.ReplaceDB(db)
	return a
}

type alphaAmmV3PoolTickDo struct{ gen.DO }

type IAlphaAmmV3PoolTickDo interface {
	gen.SubQuery
	Debug() IAlphaAmmV3PoolTickDo
	WithContext(ctx context.Context) IAlphaAmmV3PoolTickDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlphaAmmV3PoolTickDo
	WriteDB() IAlphaAmmV3PoolTickDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlphaAmmV3PoolTickDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlphaAmmV3PoolTickDo
	Not(conds ...gen.Condition) IAlphaAmmV3PoolTickDo
	Or(conds ...gen.Condition) IAlphaAmmV3PoolTickDo
	Select(conds ...field.Expr) IAlphaAmmV3PoolTickDo
	Where(conds ...gen.Condition) IAlphaAmmV3PoolTickDo
	Order(conds ...field.Expr) IAlphaAmmV3PoolTickDo
	Distinct(cols ...field.Expr) IAlphaAmmV3PoolTickDo
	Omit(cols ...field.Expr) IAlphaAmmV3PoolTickDo
	Join(table schema.Tabler, on ...field.Expr) IAlphaAmmV3PoolTickDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlphaAmmV3PoolTickDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlphaAmmV3PoolTickDo
	Group(cols ...field.Expr) IAlphaAmmV3PoolTickDo
	Having(conds ...gen.Condition) IAlphaAmmV3PoolTickDo
	Limit(limit int) IAlphaAmmV3PoolTickDo
	Offset(offset int) IAlphaAmmV3PoolTickDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlphaAmmV3PoolTickDo
	Unscoped() IAlphaAmmV3PoolTickDo
	Create(values ...*sqlmodel.AlphaAmmV3PoolTick) error
	CreateInBatches(values []*sqlmodel.AlphaAmmV3PoolTick, batchSize int) error
	Save(values ...*sqlmodel.AlphaAmmV3PoolTick) error
	First() (*sqlmodel.AlphaAmmV3PoolTick, error)
	Take() (*sqlmodel.AlphaAmmV3PoolTick, error)
	Last() (*sqlmodel.AlphaAmmV3PoolTick, error)
	Find() ([]*sqlmodel.AlphaAmmV3PoolTick, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlmodel.AlphaAmmV3PoolTick, err error)
	FindInBatches(result *[]*sqlmodel.AlphaAmmV3PoolTick, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*sqlmodel.AlphaAmmV3PoolTick) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlphaAmmV3PoolTickDo
	Assign(attrs ...field.AssignExpr) IAlphaAmmV3PoolTickDo
	Joins(fields ...field.RelationField) IAlphaAmmV3PoolTickDo
	Preload(fields ...field.RelationField) IAlphaAmmV3PoolTickDo
	FirstOrInit() (*sqlmodel.AlphaAmmV3PoolTick, error)
	FirstOrCreate() (*sqlmodel.AlphaAmmV3PoolTick, error)
	FindByPage(offset int, limit int) (result []*sqlmodel.AlphaAmmV3PoolTick, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlphaAmmV3PoolTickDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alphaAmmV3PoolTickDo) Debug() IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Debug())
}

func (a alphaAmmV3PoolTickDo) WithContext(ctx context.Context) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alphaAmmV3PoolTickDo) ReadDB() IAlphaAmmV3PoolTickDo {
	return a.Clauses(dbresolver.Read)
}

func (a alphaAmmV3PoolTickDo) WriteDB() IAlphaAmmV3PoolTickDo {
	return a.Clauses(dbresolver.Write)
}

func (a alphaAmmV3PoolTickDo) Session(config *gorm.Session) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Session(config))
}

func (a alphaAmmV3PoolTickDo) Clauses(conds ...clause.Expression) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alphaAmmV3PoolTickDo) Returning(value interface{}, columns ...string) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alphaAmmV3PoolTickDo) Not(conds ...gen.Condition) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alphaAmmV3PoolTickDo) Or(conds ...gen.Condition) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alphaAmmV3PoolTickDo) Select(conds ...field.Expr) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alphaAmmV3PoolTickDo) Where(conds ...gen.Condition) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alphaAmmV3PoolTickDo) Order(conds ...field.Expr) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alphaAmmV3PoolTickDo) Distinct(cols ...field.Expr) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alphaAmmV3PoolTickDo) Omit(cols ...field.Expr) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alphaAmmV3PoolTickDo) Join(table schema.Tabler, on ...field.Expr) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alphaAmmV3PoolTickDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alphaAmmV3PoolTickDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alphaAmmV3PoolTickDo) Group(cols ...field.Expr) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alphaAmmV3PoolTickDo) Having(conds ...gen.Condition) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alphaAmmV3PoolTickDo) Limit(limit int) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alphaAmmV3PoolTickDo) Offset(offset int) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alphaAmmV3PoolTickDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alphaAmmV3PoolTickDo) Unscoped() IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alphaAmmV3PoolTickDo) Create(values ...*sqlmodel.AlphaAmmV3PoolTick) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alphaAmmV3PoolTickDo) CreateInBatches(values []*sqlmodel.AlphaAmmV3PoolTick, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alphaAmmV3PoolTickDo) Save(values ...*sqlmodel.AlphaAmmV3PoolTick) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alphaAmmV3PoolTickDo) First() (*sqlmodel.AlphaAmmV3PoolTick, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaAmmV3PoolTick), nil
	}
}

func (a alphaAmmV3PoolTickDo) Take() (*sqlmodel.AlphaAmmV3PoolTick, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaAmmV3PoolTick), nil
	}
}

func (a alphaAmmV3PoolTickDo) Last() (*sqlmodel.AlphaAmmV3PoolTick, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaAmmV3PoolTick), nil
	}
}

func (a alphaAmmV3PoolTickDo) Find() ([]*sqlmodel.AlphaAmmV3PoolTick, error) {
	result, err := a.DO.Find()
	return result.([]*sqlmodel.AlphaAmmV3PoolTick), err
}

func (a alphaAmmV3PoolTickDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlmodel.AlphaAmmV3PoolTick, err error) {
	buf := make([]*sqlmodel.AlphaAmmV3PoolTick, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alphaAmmV3PoolTickDo) FindInBatches(result *[]*sqlmodel.AlphaAmmV3PoolTick, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alphaAmmV3PoolTickDo) Attrs(attrs ...field.AssignExpr) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alphaAmmV3PoolTickDo) Assign(attrs ...field.AssignExpr) IAlphaAmmV3PoolTickDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alphaAmmV3PoolTickDo) Joins(fields ...field.RelationField) IAlphaAmmV3PoolTickDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alphaAmmV3PoolTickDo) Preload(fields ...field.RelationField) IAlphaAmmV3PoolTickDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alphaAmmV3PoolTickDo) FirstOrInit() (*sqlmodel.AlphaAmmV3PoolTick, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaAmmV3PoolTick), nil
	}
}

func (a alphaAmmV3PoolTickDo) FirstOrCreate() (*sqlmodel.AlphaAmmV3PoolTick, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaAmmV3PoolTick), nil
	}
}

func (a alphaAmmV3PoolTickDo) FindByPage(offset int, limit int) (result []*sqlmodel.AlphaAmmV3PoolTick, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alphaAmmV3PoolTickDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alphaAmmV3PoolTickDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alphaAmmV3PoolTickDo) Delete(models ...*sqlmodel.AlphaAmmV3PoolTick) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alphaAmmV3PoolTickDo) withDO(do gen.Dao) *alphaAmmV3PoolTickDo {
	a.DO = *do.(*gen.DO)
	return a
}
