// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"alpha-amm-engine/internal/dao/sqlmodel"
)

func newAlphaPoolLiquidityEvent(db *gorm.DB, opts ...gen.DOOption) alphaPoolLiquidityEvent {
	_alphaPoolLiquidityEvent := alphaPoolLiquidityEvent{}

	_alphaPoolLiquidityEvent.alphaPoolLiquidityEventDo.UseDB(db, opts...)
	_alphaPoolLiquidityEvent.alphaPoolLiquidityEventDo.UseModel(&sqlmodel.AlphaPoolLiquidityEvent{})

	tableName := _alphaPoolLiquidityEvent.alphaPoolLiquidityEventDo.TableName()
	_alphaPoolLiquidityEvent.ALL = field.NewAsterisk(tableName)
	_alphaPoolLiquidityEvent.ID = field.NewInt64(tableName, "id")
	_alphaPoolLiquidityEvent.ChainID = field.NewInt32(tableName, "chain_id")
	_alphaPoolLiquidityEvent.PoolAddress = field.NewString(tableName, "pool_address")
	_alphaPoolLiquidityEvent.TxHash = field.NewString(tableName, "tx_hash")
	_alphaPoolLiquidityEvent.LogIndex = field.NewInt32(tableName, "log_index")
	_alphaPoolLiquidityEvent.EventName = field.NewString(tableName, "event_name")
	_alphaPoolLiquidityEvent.Provider = field.NewString(tableName, "provider")
	_alphaPoolLiquidityEvent.Amount0 = field.NewString(tableName, "amount0")
	_alphaPoolLiquidityEvent.Amount1 = field.NewString(tableName, "amount1")
	_alphaPoolLiquidityEvent.TickLower = field.NewInt32(tableName, "tick_lower")
	_alphaPoolLiquidityEvent.TickUpper = field.NewInt32(tableName, "tick_upper")
	_alphaPoolLiquidityEvent.LiquidityDelta = field.NewString(tableName, "liquidity_delta")
	_alphaPoolLiquidityEvent.BlockNumber = field.NewInt64(tableName, "block_number")
	_alphaPoolLiquidityEvent.BlockTimestamp = field.NewTime(tableName, "block_timestamp")
	_alphaPoolLiquidityEvent.CreatedAt = field.NewTime(tableName, "created_at")

	_alphaPoolLiquidityEvent.fillFieldMap()

	return _alphaPoolLiquidityEvent
}

// alphaPoolLiquidityEvent LP流动性增减事件记录表
type alphaPoolLiquidityEvent struct {
	alphaPoolLiquidityEventDo alphaPoolLiquidityEventDo

	ALL            field.Asterisk
	ID             field.Int64
	ChainID        field.Int32  // 链ID
	PoolAddress    field.String // 池子地址
	TxHash         field.String // 交易哈希
	LogIndex       field.Int32  // 日志索引(防单笔交易多事件)
	EventName      field.String // MINT:添加, BURN:移除, COLLECT:提取收益(V3)
	Provider       field.String // 流动性提供者地址
	Amount0        field.String // Token0 变动数量
	Amount1        field.String // Token1 变动数量
	TickLower      field.Int32  // V3: 价格区间下限
	TickUpper      field.Int32  // V3: 价格区间上限
	LiquidityDelta field.String // V3: 流动性数量变化(sqrt)
	BlockNumber    field.Int64  // 区块高度
	BlockTimestamp field.Time   // 区块时间(由链上提供)
	CreatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (a alphaPoolLiquidityEvent) Table(newTableName string) *alphaPoolLiquidityEvent {
	a.alphaPoolLiquidityEventDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alphaPoolLiquidityEvent) As(alias string) *alphaPoolLiquidityEvent {
	a.alphaPoolLiquidityEventDo.DO = *(a.alphaPoolLiquidityEventDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alphaPoolLiquidityEvent) updateTableName(table string) *alphaPoolLiquidityEvent {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.ChainID = field.NewInt32(table, "chain_id")
	a.PoolAddress = field.NewString(table, "pool_address")
	a.TxHash = field.NewString(table, "tx_hash")
	a.LogIndex = field.NewInt32(table, "log_index")
	a.EventName = field.NewString(table, "event_name")
	a.Provider = field.NewString(table, "provider")
	a.Amount0 = field.NewString(table, "amount0")
	a.Amount1 = field.NewString(table, "amount1")
	a.TickLower = field.NewInt32(table, "tick_lower")
	a.TickUpper = field.NewInt32(table, "tick_upper")
	a.LiquidityDelta = field.NewString(table, "liquidity_delta")
	a.BlockNumber = field.NewInt64(table, "block_number")
	a.BlockTimestamp = field.NewTime(table, "block_timestamp")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *alphaPoolLiquidityEvent) WithContext(ctx context.Context) IAlphaPoolLiquidityEventDo {
	return a.alphaPoolLiquidityEventDo.WithContext(ctx)
}

func (a alphaPoolLiquidityEvent) TableName() string { return a.alphaPoolLiquidityEventDo.TableName() }

func (a alphaPoolLiquidityEvent) Alias() string { return a.alphaPoolLiquidityEventDo.Alias() }

func (a alphaPoolLiquidityEvent) Columns(cols ...field.Expr) gen.Columns {
	return a.alphaPoolLiquidityEventDo.Columns(cols...)
}

func (a *alphaPoolLiquidityEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alphaPoolLiquidityEvent) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 15)
	a.fieldMap["id"] = a.ID
	a.fieldMap["chain_id"] = a.ChainID
	a.fieldMap["pool_address"] = a.PoolAddress
	a.fieldMap["tx_hash"] = a.TxHash
	a.fieldMap["log_index"] = a.LogIndex
	a.fieldMap["event_name"] = a.EventName
	a.fieldMap["provider"] = a.Provider
	a.fieldMap["amount0"] = a.Amount0
	a.fieldMap["amount1"] = a.Amount1
	a.fieldMap["tick_lower"] = a.TickLower
	a.fieldMap["tick_upper"] = a.TickUpper
	a.fieldMap["liquidity_delta"] = a.LiquidityDelta
	a.fieldMap["block_number"] = a.BlockNumber
	a.fieldMap["block_timestamp"] = a.BlockTimestamp
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a alphaPoolLiquidityEvent) clone(db *gorm.DB) alphaPoolLiquidityEvent {
	a.alphaPoolLiquidityEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alphaPoolLiquidityEvent) replaceDB(db *gorm.DB) alphaPoolLiquidityEvent {
	a.alphaPoolLiquidityEventDo.ReplaceDB(db)
	return a
}

type alphaPoolLiquidityEventDo struct{ gen.DO }

type IAlphaPoolLiquidityEventDo interface {
	gen.SubQuery
	Debug() IAlphaPoolLiquidityEventDo
	WithContext(ctx context.Context) IAlphaPoolLiquidityEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlphaPoolLiquidityEventDo
	WriteDB() IAlphaPoolLiquidityEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlphaPoolLiquidityEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlphaPoolLiquidityEventDo
	Not(conds ...gen.Condition) IAlphaPoolLiquidityEventDo
	Or(conds ...gen.Condition) IAlphaPoolLiquidityEventDo
	Select(conds ...field.Expr) IAlphaPoolLiquidityEventDo
	Where(conds ...gen.Condition) IAlphaPoolLiquidityEventDo
	Order(conds ...field.Expr) IAlphaPoolLiquidityEventDo
	Distinct(cols ...field.Expr) IAlphaPoolLiquidityEventDo
	Omit(cols ...field.Expr) IAlphaPoolLiquidityEventDo
	Join(table schema.Tabler, on ...field.Expr) IAlphaPoolLiquidityEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlphaPoolLiquidityEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlphaPoolLiquidityEventDo
	Group(cols ...field.Expr) IAlphaPoolLiquidityEventDo
	Having(conds ...gen.Condition) IAlphaPoolLiquidityEventDo
	Limit(limit int) IAlphaPoolLiquidityEventDo
	Offset(offset int) IAlphaPoolLiquidityEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlphaPoolLiquidityEventDo
	Unscoped() IAlphaPoolLiquidityEventDo
	Create(values ...*sqlmodel.AlphaPoolLiquidityEvent) error
	CreateInBatches(values []*sqlmodel.AlphaPoolLiquidityEvent, batchSize int) error
	Save(values ...*sqlmodel.AlphaPoolLiquidityEvent) error
	First() (*sqlmodel.AlphaPoolLiquidityEvent, error)
	Take() (*sqlmodel.AlphaPoolLiquidityEvent, error)
	Last() (*sqlmodel.AlphaPoolLiquidityEvent, error)
	Find() ([]*sqlmodel.AlphaPoolLiquidityEvent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlmodel.AlphaPoolLiquidityEvent, err error)
	FindInBatches(result *[]*sqlmodel.AlphaPoolLiquidityEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*sqlmodel.AlphaPoolLiquidityEvent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlphaPoolLiquidityEventDo
	Assign(attrs ...field.AssignExpr) IAlphaPoolLiquidityEventDo
	Joins(fields ...field.RelationField) IAlphaPoolLiquidityEventDo
	Preload(fields ...field.RelationField) IAlphaPoolLiquidityEventDo
	FirstOrInit() (*sqlmodel.AlphaPoolLiquidityEvent, error)
	FirstOrCreate() (*sqlmodel.AlphaPoolLiquidityEvent, error)
	FindByPage(offset int, limit int) (result []*sqlmodel.AlphaPoolLiquidityEvent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlphaPoolLiquidityEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alphaPoolLiquidityEventDo) Debug() IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Debug())
}

func (a alphaPoolLiquidityEventDo) WithContext(ctx context.Context) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alphaPoolLiquidityEventDo) ReadDB() IAlphaPoolLiquidityEventDo {
	return a.Clauses(dbresolver.Read)
}

func (a alphaPoolLiquidityEventDo) WriteDB() IAlphaPoolLiquidityEventDo {
	return a.Clauses(dbresolver.Write)
}

func (a alphaPoolLiquidityEventDo) Session(config *gorm.Session) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Session(config))
}

func (a alphaPoolLiquidityEventDo) Clauses(conds ...clause.Expression) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alphaPoolLiquidityEventDo) Returning(value interface{}, columns ...string) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alphaPoolLiquidityEventDo) Not(conds ...gen.Condition) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alphaPoolLiquidityEventDo) Or(conds ...gen.Condition) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alphaPoolLiquidityEventDo) Select(conds ...field.Expr) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alphaPoolLiquidityEventDo) Where(conds ...gen.Condition) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alphaPoolLiquidityEventDo) Order(conds ...field.Expr) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alphaPoolLiquidityEventDo) Distinct(cols ...field.Expr) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alphaPoolLiquidityEventDo) Omit(cols ...field.Expr) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alphaPoolLiquidityEventDo) Join(table schema.Tabler, on ...field.Expr) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alphaPoolLiquidityEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alphaPoolLiquidityEventDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alphaPoolLiquidityEventDo) Group(cols ...field.Expr) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alphaPoolLiquidityEventDo) Having(conds ...gen.Condition) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alphaPoolLiquidityEventDo) Limit(limit int) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alphaPoolLiquidityEventDo) Offset(offset int) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alphaPoolLiquidityEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alphaPoolLiquidityEventDo) Unscoped() IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alphaPoolLiquidityEventDo) Create(values ...*sqlmodel.AlphaPoolLiquidityEvent) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alphaPoolLiquidityEventDo) CreateInBatches(values []*sqlmodel.AlphaPoolLiquidityEvent, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alphaPoolLiquidityEventDo) Save(values ...*sqlmodel.AlphaPoolLiquidityEvent) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alphaPoolLiquidityEventDo) First() (*sqlmodel.AlphaPoolLiquidityEvent, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaPoolLiquidityEvent), nil
	}
}

func (a alphaPoolLiquidityEventDo) Take() (*sqlmodel.AlphaPoolLiquidityEvent, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaPoolLiquidityEvent), nil
	}
}

func (a alphaPoolLiquidityEventDo) Last() (*sqlmodel.AlphaPoolLiquidityEvent, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaPoolLiquidityEvent), nil
	}
}

func (a alphaPoolLiquidityEventDo) Find() ([]*sqlmodel.AlphaPoolLiquidityEvent, error) {
	result, err := a.DO.Find()
	return result.([]*sqlmodel.AlphaPoolLiquidityEvent), err
}

func (a alphaPoolLiquidityEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlmodel.AlphaPoolLiquidityEvent, err error) {
	buf := make([]*sqlmodel.AlphaPoolLiquidityEvent, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alphaPoolLiquidityEventDo) FindInBatches(result *[]*sqlmodel.AlphaPoolLiquidityEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alphaPoolLiquidityEventDo) Attrs(attrs ...field.AssignExpr) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alphaPoolLiquidityEventDo) Assign(attrs ...field.AssignExpr) IAlphaPoolLiquidityEventDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alphaPoolLiquidityEventDo) Joins(fields ...field.RelationField) IAlphaPoolLiquidityEventDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alphaPoolLiquidityEventDo) Preload(fields ...field.RelationField) IAlphaPoolLiquidityEventDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alphaPoolLiquidityEventDo) FirstOrInit() (*sqlmodel.AlphaPoolLiquidityEvent, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaPoolLiquidityEvent), nil
	}
}

func (a alphaPoolLiquidityEventDo) FirstOrCreate() (*sqlmodel.AlphaPoolLiquidityEvent, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaPoolLiquidityEvent), nil
	}
}

func (a alphaPoolLiquidityEventDo) FindByPage(offset int, limit int) (result []*sqlmodel.AlphaPoolLiquidityEvent, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alphaPoolLiquidityEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alphaPoolLiquidityEventDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alphaPoolLiquidityEventDo) Delete(models ...*sqlmodel.AlphaPoolLiquidityEvent) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alphaPoolLiquidityEventDo) withDO(do gen.Dao) *alphaPoolLiquidityEventDo {
	a.DO = *do.(*gen.DO)
	return a
}
