// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"alpha-amm-engine/internal/dao/sqlmodel"
)

func newAlphaToken(db *gorm.DB, opts ...gen.DOOption) alphaToken {
	_alphaToken := alphaToken{}

	_alphaToken.alphaTokenDo.UseDB(db, opts...)
	_alphaToken.alphaTokenDo.UseModel(&sqlmodel.AlphaToken{})

	tableName := _alphaToken.alphaTokenDo.TableName()
	_alphaToken.ALL = field.NewAsterisk(tableName)
	_alphaToken.ID = field.NewInt64(tableName, "id")
	_alphaToken.Symbol = field.NewString(tableName, "symbol")
	_alphaToken.Name = field.NewString(tableName, "name")
	_alphaToken.Address = field.NewString(tableName, "address")
	_alphaToken.IsNative = field.NewBool(tableName, "is_native")
	_alphaToken.Decimals = field.NewInt32(tableName, "decimals")
	_alphaToken.ChainID = field.NewString(tableName, "chain_id")
	_alphaToken.CreatedAt = field.NewTime(tableName, "created_at")

	_alphaToken.fillFieldMap()

	return _alphaToken
}

// alphaToken token信息表
type alphaToken struct {
	alphaTokenDo alphaTokenDo

	ALL       field.Asterisk
	ID        field.Int64
	Symbol    field.String
	Name      field.String
	Address   field.String
	IsNative  field.Bool // 是否是原生代币
	Decimals  field.Int32
	ChainID   field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (a alphaToken) Table(newTableName string) *alphaToken {
	a.alphaTokenDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alphaToken) As(alias string) *alphaToken {
	a.alphaTokenDo.DO = *(a.alphaTokenDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alphaToken) updateTableName(table string) *alphaToken {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.Symbol = field.NewString(table, "symbol")
	a.Name = field.NewString(table, "name")
	a.Address = field.NewString(table, "address")
	a.IsNative = field.NewBool(table, "is_native")
	a.Decimals = field.NewInt32(table, "decimals")
	a.ChainID = field.NewString(table, "chain_id")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *alphaToken) WithContext(ctx context.Context) IAlphaTokenDo {
	return a.alphaTokenDo.WithContext(ctx)
}

func (a alphaToken) TableName() string { return a.alphaTokenDo.TableName() }

func (a alphaToken) Alias() string { return a.alphaTokenDo.Alias() }

func (a alphaToken) Columns(cols ...field.Expr) gen.Columns { return a.alphaTokenDo.Columns(cols...) }

func (a *alphaToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alphaToken) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["symbol"] = a.Symbol
	a.fieldMap["name"] = a.Name
	a.fieldMap["address"] = a.Address
	a.fieldMap["is_native"] = a.IsNative
	a.fieldMap["decimals"] = a.Decimals
	a.fieldMap["chain_id"] = a.ChainID
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a alphaToken) clone(db *gorm.DB) alphaToken {
	a.alphaTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alphaToken) replaceDB(db *gorm.DB) alphaToken {
	a.alphaTokenDo.ReplaceDB(db)
	return a
}

type alphaTokenDo struct{ gen.DO }

type IAlphaTokenDo interface {
	gen.SubQuery
	Debug() IAlphaTokenDo
	WithContext(ctx context.Context) IAlphaTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlphaTokenDo
	WriteDB() IAlphaTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlphaTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlphaTokenDo
	Not(conds ...gen.Condition) IAlphaTokenDo
	Or(conds ...gen.Condition) IAlphaTokenDo
	Select(conds ...field.Expr) IAlphaTokenDo
	Where(conds ...gen.Condition) IAlphaTokenDo
	Order(conds ...field.Expr) IAlphaTokenDo
	Distinct(cols ...field.Expr) IAlphaTokenDo
	Omit(cols ...field.Expr) IAlphaTokenDo
	Join(table schema.Tabler, on ...field.Expr) IAlphaTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlphaTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlphaTokenDo
	Group(cols ...field.Expr) IAlphaTokenDo
	Having(conds ...gen.Condition) IAlphaTokenDo
	Limit(limit int) IAlphaTokenDo
	Offset(offset int) IAlphaTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlphaTokenDo
	Unscoped() IAlphaTokenDo
	Create(values ...*sqlmodel.AlphaToken) error
	CreateInBatches(values []*sqlmodel.AlphaToken, batchSize int) error
	Save(values ...*sqlmodel.AlphaToken) error
	First() (*sqlmodel.AlphaToken, error)
	Take() (*sqlmodel.AlphaToken, error)
	Last() (*sqlmodel.AlphaToken, error)
	Find() ([]*sqlmodel.AlphaToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlmodel.AlphaToken, err error)
	FindInBatches(result *[]*sqlmodel.AlphaToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*sqlmodel.AlphaToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlphaTokenDo
	Assign(attrs ...field.AssignExpr) IAlphaTokenDo
	Joins(fields ...field.RelationField) IAlphaTokenDo
	Preload(fields ...field.RelationField) IAlphaTokenDo
	FirstOrInit() (*sqlmodel.AlphaToken, error)
	FirstOrCreate() (*sqlmodel.AlphaToken, error)
	FindByPage(offset int, limit int) (result []*sqlmodel.AlphaToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlphaTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alphaTokenDo) Debug() IAlphaTokenDo {
	return a.withDO(a.DO.Debug())
}

func (a alphaTokenDo) WithContext(ctx context.Context) IAlphaTokenDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alphaTokenDo) ReadDB() IAlphaTokenDo {
	return a.Clauses(dbresolver.Read)
}

func (a alphaTokenDo) WriteDB() IAlphaTokenDo {
	return a.Clauses(dbresolver.Write)
}

func (a alphaTokenDo) Session(config *gorm.Session) IAlphaTokenDo {
	return a.withDO(a.DO.Session(config))
}

func (a alphaTokenDo) Clauses(conds ...clause.Expression) IAlphaTokenDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alphaTokenDo) Returning(value interface{}, columns ...string) IAlphaTokenDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alphaTokenDo) Not(conds ...gen.Condition) IAlphaTokenDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alphaTokenDo) Or(conds ...gen.Condition) IAlphaTokenDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alphaTokenDo) Select(conds ...field.Expr) IAlphaTokenDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alphaTokenDo) Where(conds ...gen.Condition) IAlphaTokenDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alphaTokenDo) Order(conds ...field.Expr) IAlphaTokenDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alphaTokenDo) Distinct(cols ...field.Expr) IAlphaTokenDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alphaTokenDo) Omit(cols ...field.Expr) IAlphaTokenDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alphaTokenDo) Join(table schema.Tabler, on ...field.Expr) IAlphaTokenDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alphaTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlphaTokenDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alphaTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlphaTokenDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alphaTokenDo) Group(cols ...field.Expr) IAlphaTokenDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alphaTokenDo) Having(conds ...gen.Condition) IAlphaTokenDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alphaTokenDo) Limit(limit int) IAlphaTokenDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alphaTokenDo) Offset(offset int) IAlphaTokenDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alphaTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlphaTokenDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alphaTokenDo) Unscoped() IAlphaTokenDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alphaTokenDo) Create(values ...*sqlmodel.AlphaToken) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alphaTokenDo) CreateInBatches(values []*sqlmodel.AlphaToken, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alphaTokenDo) Save(values ...*sqlmodel.AlphaToken) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alphaTokenDo) First() (*sqlmodel.AlphaToken, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaToken), nil
	}
}

func (a alphaTokenDo) Take() (*sqlmodel.AlphaToken, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaToken), nil
	}
}

func (a alphaTokenDo) Last() (*sqlmodel.AlphaToken, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaToken), nil
	}
}

func (a alphaTokenDo) Find() ([]*sqlmodel.AlphaToken, error) {
	result, err := a.DO.Find()
	return result.([]*sqlmodel.AlphaToken), err
}

func (a alphaTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlmodel.AlphaToken, err error) {
	buf := make([]*sqlmodel.AlphaToken, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alphaTokenDo) FindInBatches(result *[]*sqlmodel.AlphaToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alphaTokenDo) Attrs(attrs ...field.AssignExpr) IAlphaTokenDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alphaTokenDo) Assign(attrs ...field.AssignExpr) IAlphaTokenDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alphaTokenDo) Joins(fields ...field.RelationField) IAlphaTokenDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alphaTokenDo) Preload(fields ...field.RelationField) IAlphaTokenDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alphaTokenDo) FirstOrInit() (*sqlmodel.AlphaToken, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaToken), nil
	}
}

func (a alphaTokenDo) FirstOrCreate() (*sqlmodel.AlphaToken, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.AlphaToken), nil
	}
}

func (a alphaTokenDo) FindByPage(offset int, limit int) (result []*sqlmodel.AlphaToken, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alphaTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alphaTokenDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alphaTokenDo) Delete(models ...*sqlmodel.AlphaToken) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alphaTokenDo) withDO(do gen.Dao) *alphaTokenDo {
	a.DO = *do.(*gen.DO)
	return a
}
