// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"alpha-amm-engine/internal/dao/sqlmodel"
)

func newConfigPair(db *gorm.DB, opts ...gen.DOOption) configPair {
	_configPair := configPair{}

	_configPair.configPairDo.UseDB(db, opts...)
	_configPair.configPairDo.UseModel(&sqlmodel.ConfigPair{})

	tableName := _configPair.configPairDo.TableName()
	_configPair.ALL = field.NewAsterisk(tableName)
	_configPair.ID = field.NewInt64(tableName, "id")
	_configPair.Token0Address = field.NewString(tableName, "token0_address")
	_configPair.Token1Address = field.NewString(tableName, "token1_address")
	_configPair.FeeTier = field.NewInt32(tableName, "fee_tier")
	_configPair.TickSpace = field.NewInt32(tableName, "tick_space")
	_configPair.PoolType = field.NewString(tableName, "pool_type")
	_configPair.CreatedAt = field.NewTime(tableName, "created_at")

	_configPair.fillFieldMap()

	return _configPair
}

type configPair struct {
	configPairDo configPairDo

	ALL           field.Asterisk
	ID            field.Int64
	Token0Address field.String
	Token1Address field.String
	FeeTier       field.Int32
	TickSpace     field.Int32
	PoolType      field.String
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (c configPair) Table(newTableName string) *configPair {
	c.configPairDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c configPair) As(alias string) *configPair {
	c.configPairDo.DO = *(c.configPairDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *configPair) updateTableName(table string) *configPair {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Token0Address = field.NewString(table, "token0_address")
	c.Token1Address = field.NewString(table, "token1_address")
	c.FeeTier = field.NewInt32(table, "fee_tier")
	c.TickSpace = field.NewInt32(table, "tick_space")
	c.PoolType = field.NewString(table, "pool_type")
	c.CreatedAt = field.NewTime(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *configPair) WithContext(ctx context.Context) IConfigPairDo {
	return c.configPairDo.WithContext(ctx)
}

func (c configPair) TableName() string { return c.configPairDo.TableName() }

func (c configPair) Alias() string { return c.configPairDo.Alias() }

func (c configPair) Columns(cols ...field.Expr) gen.Columns { return c.configPairDo.Columns(cols...) }

func (c *configPair) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *configPair) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["id"] = c.ID
	c.fieldMap["token0_address"] = c.Token0Address
	c.fieldMap["token1_address"] = c.Token1Address
	c.fieldMap["fee_tier"] = c.FeeTier
	c.fieldMap["tick_space"] = c.TickSpace
	c.fieldMap["pool_type"] = c.PoolType
	c.fieldMap["created_at"] = c.CreatedAt
}

func (c configPair) clone(db *gorm.DB) configPair {
	c.configPairDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c configPair) replaceDB(db *gorm.DB) configPair {
	c.configPairDo.ReplaceDB(db)
	return c
}

type configPairDo struct{ gen.DO }

type IConfigPairDo interface {
	gen.SubQuery
	Debug() IConfigPairDo
	WithContext(ctx context.Context) IConfigPairDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConfigPairDo
	WriteDB() IConfigPairDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConfigPairDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConfigPairDo
	Not(conds ...gen.Condition) IConfigPairDo
	Or(conds ...gen.Condition) IConfigPairDo
	Select(conds ...field.Expr) IConfigPairDo
	Where(conds ...gen.Condition) IConfigPairDo
	Order(conds ...field.Expr) IConfigPairDo
	Distinct(cols ...field.Expr) IConfigPairDo
	Omit(cols ...field.Expr) IConfigPairDo
	Join(table schema.Tabler, on ...field.Expr) IConfigPairDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConfigPairDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConfigPairDo
	Group(cols ...field.Expr) IConfigPairDo
	Having(conds ...gen.Condition) IConfigPairDo
	Limit(limit int) IConfigPairDo
	Offset(offset int) IConfigPairDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConfigPairDo
	Unscoped() IConfigPairDo
	Create(values ...*sqlmodel.ConfigPair) error
	CreateInBatches(values []*sqlmodel.ConfigPair, batchSize int) error
	Save(values ...*sqlmodel.ConfigPair) error
	First() (*sqlmodel.ConfigPair, error)
	Take() (*sqlmodel.ConfigPair, error)
	Last() (*sqlmodel.ConfigPair, error)
	Find() ([]*sqlmodel.ConfigPair, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlmodel.ConfigPair, err error)
	FindInBatches(result *[]*sqlmodel.ConfigPair, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*sqlmodel.ConfigPair) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConfigPairDo
	Assign(attrs ...field.AssignExpr) IConfigPairDo
	Joins(fields ...field.RelationField) IConfigPairDo
	Preload(fields ...field.RelationField) IConfigPairDo
	FirstOrInit() (*sqlmodel.ConfigPair, error)
	FirstOrCreate() (*sqlmodel.ConfigPair, error)
	FindByPage(offset int, limit int) (result []*sqlmodel.ConfigPair, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConfigPairDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c configPairDo) Debug() IConfigPairDo {
	return c.withDO(c.DO.Debug())
}

func (c configPairDo) WithContext(ctx context.Context) IConfigPairDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c configPairDo) ReadDB() IConfigPairDo {
	return c.Clauses(dbresolver.Read)
}

func (c configPairDo) WriteDB() IConfigPairDo {
	return c.Clauses(dbresolver.Write)
}

func (c configPairDo) Session(config *gorm.Session) IConfigPairDo {
	return c.withDO(c.DO.Session(config))
}

func (c configPairDo) Clauses(conds ...clause.Expression) IConfigPairDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c configPairDo) Returning(value interface{}, columns ...string) IConfigPairDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c configPairDo) Not(conds ...gen.Condition) IConfigPairDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c configPairDo) Or(conds ...gen.Condition) IConfigPairDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c configPairDo) Select(conds ...field.Expr) IConfigPairDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c configPairDo) Where(conds ...gen.Condition) IConfigPairDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c configPairDo) Order(conds ...field.Expr) IConfigPairDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c configPairDo) Distinct(cols ...field.Expr) IConfigPairDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c configPairDo) Omit(cols ...field.Expr) IConfigPairDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c configPairDo) Join(table schema.Tabler, on ...field.Expr) IConfigPairDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c configPairDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConfigPairDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c configPairDo) RightJoin(table schema.Tabler, on ...field.Expr) IConfigPairDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c configPairDo) Group(cols ...field.Expr) IConfigPairDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c configPairDo) Having(conds ...gen.Condition) IConfigPairDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c configPairDo) Limit(limit int) IConfigPairDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c configPairDo) Offset(offset int) IConfigPairDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c configPairDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConfigPairDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c configPairDo) Unscoped() IConfigPairDo {
	return c.withDO(c.DO.Unscoped())
}

func (c configPairDo) Create(values ...*sqlmodel.ConfigPair) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c configPairDo) CreateInBatches(values []*sqlmodel.ConfigPair, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c configPairDo) Save(values ...*sqlmodel.ConfigPair) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c configPairDo) First() (*sqlmodel.ConfigPair, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.ConfigPair), nil
	}
}

func (c configPairDo) Take() (*sqlmodel.ConfigPair, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.ConfigPair), nil
	}
}

func (c configPairDo) Last() (*sqlmodel.ConfigPair, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.ConfigPair), nil
	}
}

func (c configPairDo) Find() ([]*sqlmodel.ConfigPair, error) {
	result, err := c.DO.Find()
	return result.([]*sqlmodel.ConfigPair), err
}

func (c configPairDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlmodel.ConfigPair, err error) {
	buf := make([]*sqlmodel.ConfigPair, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c configPairDo) FindInBatches(result *[]*sqlmodel.ConfigPair, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c configPairDo) Attrs(attrs ...field.AssignExpr) IConfigPairDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c configPairDo) Assign(attrs ...field.AssignExpr) IConfigPairDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c configPairDo) Joins(fields ...field.RelationField) IConfigPairDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c configPairDo) Preload(fields ...field.RelationField) IConfigPairDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c configPairDo) FirstOrInit() (*sqlmodel.ConfigPair, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.ConfigPair), nil
	}
}

func (c configPairDo) FirstOrCreate() (*sqlmodel.ConfigPair, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*sqlmodel.ConfigPair), nil
	}
}

func (c configPairDo) FindByPage(offset int, limit int) (result []*sqlmodel.ConfigPair, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c configPairDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c configPairDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c configPairDo) Delete(models ...*sqlmodel.ConfigPair) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *configPairDo) withDO(do gen.Dao) *configPairDo {
	c.DO = *do.(*gen.DO)
	return c
}
