// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                       = new(Query)
	AlphaAmmPool            *alphaAmmPool
	AlphaPoolLiquidityEvent *alphaPoolLiquidityEvent
	AlphaToken              *alphaToken
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AlphaAmmPool = &Q.AlphaAmmPool
	AlphaPoolLiquidityEvent = &Q.AlphaPoolLiquidityEvent
	AlphaToken = &Q.AlphaToken
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                      db,
		AlphaAmmPool:            newAlphaAmmPool(db, opts...),
		AlphaPoolLiquidityEvent: newAlphaPoolLiquidityEvent(db, opts...),
		AlphaToken:              newAlphaToken(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AlphaAmmPool            alphaAmmPool
	AlphaPoolLiquidityEvent alphaPoolLiquidityEvent
	AlphaToken              alphaToken
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		AlphaAmmPool:            q.AlphaAmmPool.clone(db),
		AlphaPoolLiquidityEvent: q.AlphaPoolLiquidityEvent.clone(db),
		AlphaToken:              q.AlphaToken.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		AlphaAmmPool:            q.AlphaAmmPool.replaceDB(db),
		AlphaPoolLiquidityEvent: q.AlphaPoolLiquidityEvent.replaceDB(db),
		AlphaToken:              q.AlphaToken.replaceDB(db),
	}
}

type queryCtx struct {
	AlphaAmmPool            IAlphaAmmPoolDo
	AlphaPoolLiquidityEvent IAlphaPoolLiquidityEventDo
	AlphaToken              IAlphaTokenDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AlphaAmmPool:            q.AlphaAmmPool.WithContext(ctx),
		AlphaPoolLiquidityEvent: q.AlphaPoolLiquidityEvent.WithContext(ctx),
		AlphaToken:              q.AlphaToken.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
